backend:
  name: git-gateway
  branch: main

media_folder: "photos/uploads"
public_folder: "photos/uploads"

publish_mode: editorial_workflow

collections:
  - name: "produk"
    label: "Produk"
    label_singular: "Produk"
    description: "Kumpulan semua produk template spreadsheet."
    folder: "content/produk"
    create: true
    
    media_folder: "photos/produk/{{id}}"
    public_folder: "photos/produk/{{id}}"
    
    slug: "{{id}}"
    extension: "json"
    format: "json"
    summary: "{{fields.judul}} | ID: {{fields.id}}"
    fields:
      - {label: "ID Produk (slug, tanpa spasi, huruf kecil)", name: "id", widget: "string"}
      - {label: "Judul", name: "judul", widget: "string"}
      - {label: "Harga", name: "harga", widget: "number", value_type: "int", default: 0}
      - {label: "Deskripsi Singkat", name: "deskripsi_singkat", widget: "text"}
      - {label: "Gambar Thumbnail (untuk galeri)", name: "gambar_thumbnail", widget: "image"}
      
      # --- BAGIAN SEO YANG BARU DITAMBAHKAN ---
      - name: "seo"
        label: "Pengaturan SEO"
        widget: "object"
        fields:
          - {label: "Meta Title", name: "meta_title", widget: "string", required: false, hint: "Judul yang muncul di Google & tab browser. Jika kosong, akan memakai Judul utama."}
          - {label: "Meta Description", name: "meta_description", widget: "text", required: false, hint: "Deskripsi singkat (maks 160 karakter) untuk hasil pencarian Google."}
          - {label: "Gambar Open Graph", name: "og_image", widget: "image", required: false, hint: "Gambar untuk preview saat dibagikan ke media sosial (rekomendasi: 1200x630px). Jika kosong, akan memakai Gambar Utama."}
      
      # --- LANJUTAN KONFIGURASI ANDA ---
      - name: "detail"
        label: "Detail Lengkap Produk"
        widget: "object"
        fields:
          - {label: "Gambar Utama", name: "gambar_utama", widget: "image"}
          - {label: "Deskripsi Lengkap", name: "deskripsi_lengkap", widget: "markdown"}
          - {label: "File PDF Panduan", name: "file_panduan_pdf", widget: "file", required: false, hint: "Unggah file PDF panduan penggunaan untuk produk ini."}
          - {label: "Link YouTube", name: "link_youtube", widget: "string", required: false}
          - {label: "Link Pembelian Langsung", name: "payment_gateway", widget: "string", required: true, hint: "https://rsquareidea.myr.id/..."}
          - name: "link_pembelian"
            label: "Link Pembelian"
            widget: "list"
            fields:
              - {label: "Platform", name: "platform", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
          - name: "galeri"
            label: "Galeri Fitur"
            widget: "list"
            fields:
              - {label: "Gambar Fitur", name: "gambar", widget: "image"}
              - {label: "Judul Fitur", name: "judul", widget: "string"}
              - {label: "Deskripsi Fitur", name: "deskripsi", widget: "markdown"}
