backend:
  name: git-gateway
  branch: main # Pastikan ini adalah branch utama Anda

# --- PERBAIKAN BERDASARKAN ERROR ---
# 1. Menambahkan kembali media_folder dan public_folder di level atas sebagai default.
# Ini adalah folder fallback jika koleksi tidak menentukannya sendiri.
media_folder: "photos/uploads"
public_folder: "/photos/uploads"

# 2. Menambahkan properti media_library yang wajib ada.
# Objek kosong {} akan menggunakan pengaturan default dari CMS.
media_library: {}
# --- AKHIR PERBAIKAN ---

collections:
  - name: "produk"
    label: "Produk"
    label_singular: "Produk"
    description: "Kumpulan semua produk template spreadsheet."
    folder: "content/produk"
    create: true
    
    # Pengaturan ini akan MENIMPA (OVERRIDE) pengaturan global di atas.
    # Jadi, untuk produk, gambar TETAP akan masuk ke folder dinamis.
    media_folder: "photos/produk/{{id}}"
    public_folder: "/photos/produk/{{id}}"
    
    slug: "{{id}}"
    extension: "json"
    format: "json"
    summary: "{{fields.judul}} | ID: {{fields.id}}"
    fields:
      - {label: "ID Produk (slug, tanpa spasi, huruf kecil)", name: "id", widget: "string"}
      - {label: "Judul", name: "judul", widget: "string"}
      - {label: "Harga", name: "harga", widget: "number", value_type: "int", default: 0}
      - {label: "Deskripsi Singkat", name: "deskripsi_singkat", widget: "text"}
      - {label: "Gambar Thumbnail (untuk galeri)", name: "gambar_thumbnail", widget: "image"}
      
      - name: "detail"
        label: "Detail Lengkap Produk"
        widget: "object"
        fields:
          - {label: "Gambar Utama", name: "gambar_utama", widget: "image"}
          - {label: "Deskripsi Lengkap", name: "deskripsi_lengkap", widget: "markdown"}
          - {label: "Link Preview Detail", name: "link_preview_detail", widget: "string", hint: "Contoh: content/preview/template-preview.html?product={{id}}"}
          - {label: "Link YouTube", name: "link_youtube", widget: "string", required: false}
          - name: "link_pembelian"
            label: "Link Pembelian"
            widget: "list"
            fields:
              - {label: "Platform", name: "platform", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
          - name: "galeri"
            label: "Galeri Fitur"
            widget: "list"
            fields:
              - {label: "Gambar Fitur", name: "gambar", widget: "image"}
              - {label: "Judul Fitur", name: "judul", widget: "string"}
              - {label: "Deskripsi Fitur", name: "deskripsi", widget: "markdown"}
