backend:
  name: git-gateway
  branch: main # Ganti ke 'master' jika itu nama branch utama Anda

media_folder: "photos/uploads"
public_folder: "/photos/uploads"

collections:
  - name: "produk"
    label: "Produk"
    label_singular: "Produk"
    description: "Kumpulan semua produk template spreadsheet."
    # Perubahan penting ada di sini. Kita menggunakan 'files' bukan 'file'
    files:
      - name: "data_produk"
        label: "Semua Data Produk"
        file: "produk.json" # File yang akan diedit
        fields: # Semua field formulir sekarang masuk ke dalam sini
          - {label: "ID Produk (slug)", name: "id", widget: "string"}
          - {label: "Judul", name: "judul", widget: "string"}
          - {label: "Harga", name: "harga", widget: "number", value_type: "int", default: 0}
          - {label: "Deskripsi Singkat", name: "deskripsi_singkat", widget: "text"}
          - {label: "Gambar Preview", name: "gambar_preview", widget: "image"}
          - name: "detail"
            label: "Detail Lengkap Produk"
            widget: "object"
            fields:
              - {label: "Gambar Utama", name: "gambar_utama", widget: "image"}
              - {label: "Deskripsi Lengkap", name: "deskripsi_lengkap", widget: "markdown"}
              - {label: "Link Preview Detail", name: "link_preview_detail", widget: "string", hint: "Contoh: templates/preview-detail.html?product=ID_PRODUK"}
              - {label: "Link YouTube", name: "link_youtube", widget: "string"}
              - name: "link_pembelian"
                label: "Link Pembelian"
                widget: "list"
                fields:
                  - {label: "Platform", name: "platform", widget: "string"}
                  - {label: "URL", name: "url", widget: "string"}
              - name: "galeri"
                label: "Galeri Fitur"
                widget: "list"
                fields:
                  - {label: "Gambar Fitur", name: "gambar", widget: "image"}
                  - {label: "Judul Fitur", name: "judul", widget: "string"}
                  - {label: "Deskripsi Fitur", name: "deskripsi", widget: "markdown"}
