backend:
  name: git-gateway
  branch: main

# Hapus atau komentari media_folder global jika ada
# media_folder: "photos"
# public_folder: "/photos"

collections:
  - name: "produk"
    label: "Produk"
    folder: "content/produk"
    create: true
    slug: "{{slug}}"
    
    # --- PERUBAHAN UTAMA DIMULAI DI SINI ---
    # Mendefinisikan folder media KHUSUS untuk koleksi produk ini
    # {{slug}} akan otomatis diganti dengan ID/slug produk
    media_folder: "photos/produk/{{slug}}"
    public_folder: "/photos/produk/{{slug}}"
    # --- AKHIR PERUBAHAN UTAMA ---

    fields:
      - { label: "ID Unik (Slug)", name: "id", widget: "string" }
      - { label: "Judul Produk", name: "judul", widget: "string" }
      - { label: "Deskripsi Singkat (untuk kartu galeri)", name: "deskripsi_singkat", widget: "text" }
      - { label: "Harga (angka saja, 0 untuk gratis)", name: "harga", widget: "number" }
      
      # Field gambar sekarang akan mengunggah ke folder dinamis di atas
      - { label: "Gambar Thumbnail (untuk galeri)", name: "gambar_thumbnail", widget: "image" }
      
      # Kita tetap menggunakan object 'detail' untuk kerapian data
      - label: "Detail Produk"
        name: "detail"
        widget: "object"
        fields:
          - { label: "Gambar Utama (di halaman detail)", name: "gambar_utama", widget: "image" }
          - { label: "Deskripsi Lengkap", name: "deskripsi_lengkap", widget: "markdown" }
          - { label: "Link Preview Detail", name: "link_preview_detail", widget: "string", required: false }
          - { label: "Link Video Youtube (Embed)", name: "link_youtube", widget: "string", required: false }
          
          - label: "Link Pembelian"
            name: "link_pembelian"
            widget: "list"
            fields:
              - { label: "Platform (e.g., Tokopedia)", name: "platform", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              
          - label: "Galeri Gambar (di halaman preview)"
            name: "galeri"
            widget: "list"
            required: false
            fields:
              - { label: "Gambar", name: "gambar", widget: "image" }
              - { label: "Judul Fitur", name: "judul", widget: "string" }
              - { label: "Deskripsi Fitur", name: "deskripsi", widget: "text" }
